support grisp_tools 2
grisp/mix_grisp pull request #7
Opened 2024-03-16 12:25 UTC by tonnenpinguin

Building on top of @LostKobrakai and @ziopio 's work this is now working.

I dropped all distillery related code, changed the logic that calculates the `apps` to use the source directory. This is required because those directories are used to assemble the overlays and the build output directories don't include those files.

I also updated the readme, as the paths mentioned don't work, since `grisp_tools` is very picky about the paths being used.

And finally I also updated the `grisp.ini.mustache` erl arguments to get things working with Elixir 1.16 & OTP 26 (the flags required for iex changed) and to deal with the fact that mix releases rely on a boot_var `RELEASE_LIB` to be set

2024-03-18 10:53 UTC, ziopio requested changes
First of all thanks very much for this contribution!
I think we can just set the bar to use elixir 1.15 and OTP 26 and update the references to point to such versions.
I also needed to add xmerl to the `mix_grisp` applications sections, otherwise `mix` does not load `xmerl` the application and grisp_tools fails.
```
  def application() do
    [
      extra_applications: [:logger, :xmerl]
    ]
  end
```
Then I will squash and merge.

2024-03-18 10:53 UTC, ziopio commented on README.md
> +                {:grisp, "~> 2.0"},
2.4 here, since that is the minimum to support OTP 26

2024-03-18 10:53 UTC, ziopio commented on README.md
> +                otp: [verson: "26.0.2"],
Better just "26" so it would pick the highest OTP pakcage version we have available for 26.

2024-03-18 10:53 UTC, ziopio commented on README.md
> +(23 in the example).
26

2024-03-18 10:53 UTC, ziopio commented on lib/mix/tasks/grisp/deploy.ex
> +        otp_version_requirement: to_charlist(config[:otp][:version] || "23"),
26

2024-03-18 10:53 UTC, ziopio commented on mix.exs
> +      elixir: "~> 1.9",
We both tested with 1.16 so I would also bump elixir to 1.16.

2024-03-18 10:53 UTC, ziopio commented on mix.exs
> +      {:grisp_tools, "~> 2.1"},
You need at least 2.4 to support `OTP > 24 `, so "~> 2.5" should be fine.

2024-03-18 11:48 UTC, tonnenpinguin commented
Thanks for the review @ziopio 
I addressed all your comments 🙂

2024-03-19 15:58 UTC, ziopio approved these changes

2024-03-19 16:13 UTC, merged